# Generated by Django 4.2.11 on 2026-02-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
